(() => {
  const map={dadaepo:['다대포 해수욕장','03:12','20:42','18:50 — 22:20',['바지락','낙지','고둥','맛조개','망둥어','꽃게']],amnam:['암남공원','03:19','20:49','19:00 — 22:30',['소라','멍게','고둥','전복','성게','불가사리']],yeongdo:['영도 흰여울','03:25','20:55','19:10 — 22:40',['소라','낙지','해삼','성게','고둥','문어']],haeundae:['해운대 청사포','03:32','21:02','19:20 — 22:50',['멍게','소라','바지락','해삼','꽃게','망둥어']],gijang:['기장 연화리','03:39','21:09','19:25 — 23:00',['멍게','바지락','전복','성게','해삼','고둥']]};
  const life={바지락:['Ruditapes philippinarum','모래와 갯벌 속에 사는 대표적인 조개입니다.','각장 3 cm','금어기 없음','species-clam.jpg'],낙지:['Octopus minor','갯벌과 바위틈에서 활동하는 두족류입니다.','지역 기준 확인','금어기 없음 (예시)','species-octopus.jpg'],문어:['Octopus vulgaris','바위와 암반 지대에 사는 두족류입니다.','지역 기준 확인','금어기 확인','species-octopus.jpg'],고둥:['Marine gastropod','바위 표면에서 발견되는 복족류입니다.','종별 상이','종별 상이','species-gastropod.jpg'],소라:['Turbo cornutus','암반 조간대에 사는 단단한 껍데기의 복족류입니다.','각장 5 cm','6.1 — 8.31 (예시)','species-turban-snail.jpg'],전복:['Haliotis discus','암반에 붙어 사는 귀 모양의 복족류입니다.','각장 10 cm (예시)','금어기 확인','species-turban-snail.jpg'],멍게:['Halocynthia roretzi','바위나 구조물에 붙어 사는 피낭동물입니다.','체장 제한 없음 (예시)','금어기 없음 (예시)','species-sea-squirt.jpg'],해삼:['Apostichopus japonicus','해저 바닥과 바위 주변에 사는 극피동물입니다.','체장 15 cm (예시)','금어기 확인','species-sea-squirt.jpg'],성게:['Sea urchin','가시를 가진 극피동물로 암반에서 발견됩니다.','지역 기준 확인','금어기 확인','species-sea-squirt.jpg'],불가사리:['Sea star','조간대의 바위와 모래에서 발견되는 극피동물입니다.','채취 비권장','지역 기준 확인','species-sea-squirt.jpg'],꽃게:['Portunus trituberculatus','모래 바닥과 갯벌에 사는 게입니다.','갑장 6.4 cm (예시)','6.21 — 8.20 (예시)','species-clam.jpg'],망둥어:['Goby','갯벌과 얕은 연안에 사는 소형 어류입니다.','지역 기준 확인','금어기 확인','species-gastropod.jpg'],맛조개:['Solen strictus','길쭉한 껍데기를 가진 갯벌 조개입니다.','각장 5 cm (예시)','금어기 확인','species-clam.jpg']};
  const root=document.querySelector('.mgn-single');let current='dadaepo';
  function sheet(){const p=map[current], el=document.querySelector('#sheet');el.innerHTML=`<button class="sheet-close" id="sheetX">×</button><p class="sheet-kicker">SELECTED POINT</p><h2>${p[0]}</h2><p class="sheet-desc">안전수칙을 확인한 뒤, 물때와 생물 규정을 살펴보세요.</p><div class="time-cards"><div><span>▲ 밀물</span><b>${p[1]}</b></div><div><span>▼ 썰물</span><b>${p[2]}</b></div><div class="best"><span>해루질 적정 시간</span><b>${p[3]}</b></div></div><h3 class="species-heading">이곳에서 만날 수 있는 생물</h3><div class="species-chips">${p[4].map(n=>`<button data-life="${n}">${n} ›</button>`).join('')}</div>`;el.classList.add('show');document.querySelector('#sheetX').onclick=()=>el.classList.remove('show');document.querySelectorAll('[data-life]').forEach(b=>b.onclick=()=>showLife(b.dataset.life));}
  function showLife(n, photo){const x=life[n];document.querySelector('#bioText').innerHTML=`<p class="sheet-kicker">${photo?'AI ANALYSIS RESULT':'SEA LIFE GUIDE'}</p><h2>${n}</h2><img class="ai-preview" src="${photo||x[4]}" alt="${n} 실사풍 이미지"><p class="analysis-badge">${x[0]}</p><p>${x[1]}</p><div class="reg-grid"><div><span>금지체장</span><b>${x[2]}</b></div><div><span>금어기</span><b>${x[3]}</b></div></div><p class="safety-note">규정은 지역과 시기에 따라 달라질 수 있습니다. 채취 전 최신 공식 고시를 확인하세요.</p>`;document.querySelector('#bio').classList.add('show')}
  root.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{current=b.dataset.p;if(localStorage.getItem('mgnSkipSafety')==='1')sheet();else document.querySelector('#safe').classList.add('show')});
  document.querySelector('#safeX').onclick=()=>{document.querySelector('#safe').classList.remove('show');sheet()};document.querySelector('#safe .dialog').insertAdjacentHTML('beforeend','<button class="primary" id="skipSafety">다시 보지 않기</button>');document.querySelector('#skipSafety').onclick=()=>{localStorage.setItem('mgnSkipSafety','1');document.querySelector('#safe').classList.remove('show');sheet()};
  document.querySelector('#singlePhoto').onchange=async e=>{const f=e.target.files[0];if(!f)return;const name=f.name.toLowerCase();if(name.includes('shark')||name.includes('상어')){document.querySelector('#bioText').innerHTML=`<p class="sheet-kicker">AI ANALYSIS RESULT</p><h2>상어류로 보입니다</h2><img class="ai-preview" src="${URL.createObjectURL(f)}" alt="촬영 사진"><p>위험 가능성이 있는 해양생물입니다. 접근하거나 포획하지 말고 안전한 거리에서 벗어나세요.</p><p class="safety-note">정확한 종 판별은 전문 기관의 영상 AI API 연동 후 제공됩니다.</p>`;document.querySelector('#bio').classList.add('show');return}document.querySelector('#bioText').innerHTML=`<p class="sheet-kicker">AI ANALYSIS</p><h2>정확한 분석이 필요해요</h2><img class="ai-preview" src="${URL.createObjectURL(f)}" alt="촬영 사진"><p>현재 앱은 임의로 종을 단정하지 않습니다. 실제 서비스에서는 해양생물 전용 비전 AI API로 사진을 분석해 신뢰도와 종을 반환합니다.</p><p class="safety-note">종을 확신할 수 없을 때는 채취·섭취하지 마세요.</p>`;document.querySelector('#bio').classList.add('show')};
})();
